version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
      - run: 
          name: "Try Perf"
          command: apt install linux-tools-generic 
          command: perf stat gzip file